# From: http://allandenot.com/devops/2015/01/31/provisioning-ec2-hosts-with-ansible.html
---
  - name: Provision ec2 box
    local_action:
      module: ec2
      key_name: "{{ ec2_keypair }}"
      group_id: "{{ ec2_security_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
      region: "{{ ec2_region }}"
      instance_tags: '{"Project":"{{ec2_tag_Project}}","Role":"{{ec2_tag_Role}}","Use":"{{ec2_tag_Use}}","ResponsibleParty":"{{ec2_tag_ResponsibleParty}}"}'
      assign_public_ip: yes
      wait: true
      count: 1
      volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
    register: ec2

  - debug: var=item
    with_items: ec2.instances

  - add_host: name={{ item.public_ip }} >
              groups=tag_Role_{{ec2_tag_Role}},tag_Use_{{ec2_tag_Use}}
              ec2_region={{ec2_region}}
              ec2_tag_Project={{ec2_tag_Project}}
              ec2_tag_Role={{ec2_tag_Role}}
              ec2_tag_Use={{ec2_tag_Use}}
              ec2_tag_ResponsibleParty={{ec2_tag_ResponsibleParty}}
              ec2_ip_address={{item.public_ip}}
    with_items: ec2.instances

  - name: Wait for the instance to boot by checking ssh
    wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances
